### ISSUE TITLE
The size of dataset

### ISSUE THREAD

**Issue by haofanwang** [neu-vi/SportsSloMo#1]
I have downloaded the videos from the given link, but there are only 8000~ clips, is there any preprocessing for cutting short clips? Thx.

**Comment by playerkk** [comment]
Thank you for your interest in our work.

The "clips" in the downloaded file, which should have been named as "sequences", are different from the ones we described in the paper. Here each sequence contains slow-motion content of a scene without any shot change. It may contain more than 9 frames, which can be useful for other tasks like dynamic view synthesis. The clip defined in the paper is just a subset of a sequence.

We will release code data processing and loader of how to use these long sequences for video frame interpolation.

**Comment by playerkk** [comment]
Close this issue. Feel free to follow up if there are other issues.
