### ISSUE TITLE
Train Validation split

### ISSUE THREAD

**Issue by yjhong89** [neu-vi/SportsSloMo#2]
Hi! Thanks for sharing work!

I've downloded data from web-demo project hompage and gonna ask how `train_vfi` and `test_vfi` work.
In `train/test_vfi.txt` files. it contains file names like this `***/****`, but raw clip data have names like `clips_****.mp4` .
Then how would I split train and test mp4 files ??

Thank you.

**Comment by JiabenChen** [comment]
Hi, thanks for your interest in our work. The guidance and the code for using SportsSloMo dataset would be released this week.
