### ISSUE TITLE
Target FPS 7.5 to 30

### ISSUE THREAD

**Issue by yjhong89** [neu-vi/SportsSloMo#3]
Hi! Thanks for sharing code and data.

What I want to do is to convert video of 7.5 fps to 30 fps. 
- Interpolate middle 3 frames given first and last frame.
Then, what if I want to fine-tune with SportsSloMo dataset, what is the correct sampling for this?
- In SportsSloMo they are converting from 30 fps to 240 fps (interpolate 7 frames)
   ![image](https://github.com/neu-vi/SportsSloMo/assets/26890721/c378893b-2c4e-4d1d-a2bb-d2a70df08ff7)
- Is it okay if sample frames [0, 4, 8, 12, 16] and [0,16] frames as input and predict [4,8,12] frames ?

**Comment by playerkk** [comment]
In the released data, we provide long sequences, which consist of continuous slow-motion content of a shot. So you should be able to use [0, 16] as input frames and estimate [4, 8, 12] intermediate ones.

**Comment by yjhong89** [comment]
Thanks!
