### ISSUE TITLE
Is there any segmentation mask alignment/registration when calculating the aux seg loss?

### ISSUE THREAD

**Issue by Juliazy** [neu-vi/SportsSloMo#4]
Hi!
Thanks for sharing the code and data!

I have a question regarding the auxiliary segmentation loss. When you use the segmentation mask of I_t and I_t_hat to calculate the CE loss and dice loss, is there any segment alignment/ registration step to make the two segmentation masks aligned (i.e. same index for same object)? If so, how did you do that? 

Thanks again!

**Comment by JiabenChen** [comment]
Hi, thanks for your interest!
In the segmentation loss design, the two segmentation masks are aligned with the "category_id" information. I will release the code for preparing segmentation masks and training using auxiliary loss soon.

**Comment by JiabenChen** [comment]
Hi, thanks for your interest!
In the segmentation loss design, the two segmentation masks are aligned with the "category_id" information. I will release the code for preparing segmentation masks and training using auxiliary loss soon.
